name: neoansi
description: ANSI escape sequences and styling micro-library written in fluent/modern Dart.
version: 0.2.0
homepage: https://github.com/neo-dart/neoansi

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  meta: ^1.7.0

dev_dependencies:
  coverage: ^1.5.0
  neodart: ^0.1.1
  path: ^1.8.2
  test: ^1.21.4
